# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dokuman.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 80, 181, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 150, 181, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.company = QtWidgets.QLabel(self.centralwidget)
        self.company.setGeometry(QtCore.QRect(160, 40, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.company.setFont(font)
        self.company.setObjectName("company")
        self.company_2 = QtWidgets.QLabel(self.centralwidget)
        self.company_2.setGeometry(QtCore.QRect(160, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.company_2.setFont(font)
        self.company_2.setObjectName("company_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 220, 181, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.company_3 = QtWidgets.QLabel(self.centralwidget)
        self.company_3.setGeometry(QtCore.QRect(160, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.company_3.setFont(font)
        self.company_3.setObjectName("company_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 150, 75, 31))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.company.setText(_translate("MainWindow", "SİRKET ADI"))
        self.company_2.setText(_translate("MainWindow", "BORC"))
        self.company_3.setText(_translate("MainWindow", "ALINACAK"))
        self.pushButton.setText(_translate("MainWindow", "İŞLE"))
    
        

def new():
    
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow1 = QtWidgets.QMainWindow()
        ui = Ui_MainWindow1()
        ui.setupUi(MainWindow1)
        MainWindow1.show()
        sys.exit(app.exec_())
        
      
