# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gecmis.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_Form3(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(100, 120, 151, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form,clicked=lambda:self.kayit())
        self.pushButton.setGeometry(QtCore.QRect(270, 120, 51, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 90, 121, 21))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def kayit(self):
        mycursor=mydb.cursor()
        sql=(f"SELECT * FROM MAVI WHERE sirket='{self.lineEdit.text()}'")
        mycursor.execute(sql)
        results=mycursor.fetchall()
        sql=(f"SELECT borc FROM MAVI WHERE sirket='{self.lineEdit.text()}'")
        mycursor.execute(sql)
        results=mycursor.fetchall()
        total_borc=0
        for borc in list(results):
            liste=list(borc)
            total_borc+=liste[0]

        sql=(f"SELECT alinacak FROM MAVI WHERE sirket='{self.lineEdit.text()}'")
        mycursor.execute(sql)
        results=mycursor.fetchall()
        total_alinacak=0
        for alinacak in results:
            liste=list(alinacak)
            total_alinacak+=liste[0]
        if total_alinacak>total_borc:
            result=total_alinacak-total_borc
            self.label.setText(f"{result}")
        else:
            result=total_alinacak-total_borc
            self.label.setText(f"{result}")
        mydb.close()    
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "OK"))
        self.label.setText(_translate("Form", "ŞİRKET ADI"))
        
mydb = mysql.connector.connect(
     host="localhost",
     user="root",
     password="admin123",
     database="mydatabase"
 )
mycursor=mydb.cursor()        



   
    
   
