# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'islem2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(170, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(250, 20, 47, 13))
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(120, 50, 181, 91))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.islem1 = QtWidgets.QLabel(self.widget)
        self.islem1.setObjectName("islem1")
        self.gridLayout.addWidget(self.islem1, 0, 0, 1, 1)
        self.islem2 = QtWidgets.QLabel(self.widget)
        self.islem2.setObjectName("islem2")
        self.gridLayout.addWidget(self.islem2, 1, 0, 1, 1)
        self.islem3 = QtWidgets.QLabel(self.widget)
        self.islem3.setObjectName("islem3")
        self.gridLayout.addWidget(self.islem3, 2, 0, 1, 1)
        self.islem4 = QtWidgets.QLabel(self.widget)
        self.islem4.setObjectName("islem4")
        self.gridLayout.addWidget(self.islem4, 3, 0, 1, 1)
        self.islem5 = QtWidgets.QLabel(self.widget)
        self.islem5.setObjectName("islem5")
        self.gridLayout.addWidget(self.islem5, 4, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
       
    
    def retranslateUi(self, Form):
        mycursor=mydb.cursor()
        sql="SELECT * FROM MAVI"
        mycursor.execute(sql)
        results=mycursor.fetchall()
        results.reverse()
        i=1
        
        for x in results:
            if i>5:
                break
            if i==1:
                islem_1=list(x)[0]+'     ,'+str(list(x)[1])+'    ,'+str(list(x)[2])
            if i==2:
                islem_2=list(x)[0]+'     ,'+str(list(x)[1])+'    ,'+str(list(x)[2])
            if i==3:
                islem_3=list(x)[0]+'     ,'+str(list(x)[1])+'    ,'+str(list(x)[2])
            if  i==4:
                islem_4=list(x)[0]+'     ,'+str(list(x)[1])+'    ,'+str(list(x)[2])
            if i==5:
                islem_5=list(x)[0]+'     ,'+str(list(x)[1])+'    ,'+str(list(x)[2])
                    
            i+=1
        
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "borç"))
        self.label_2.setText(_translate("Form", "alinacak"))
        self.islem1.setText(_translate("Form", islem_1))
        self.islem2.setText(_translate("Form", islem_2))
        self.islem3.setText(_translate("Form", islem_3))
        self.islem4.setText(_translate("Form", islem_4))
        self.islem5.setText(_translate("Form", islem_5))
        mydb.close()
  
mydb = mysql.connector.connect(
     host="localhost",
     user="root",
     password="admin123",
     database="mydatabase"
 )
mycursor=mydb.cursor()  
 


