# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'islem1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.company_3 = QtWidgets.QLabel(Form)
        self.company_3.setGeometry(QtCore.QRect(70, 170, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.company_3.setFont(font)
        self.company_3.setObjectName("company_3")
        self.company_2 = QtWidgets.QLabel(Form)
        self.company_2.setGeometry(QtCore.QRect(70, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.company_2.setFont(font)
        self.company_2.setObjectName("company_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 140, 181, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(70, 70, 181, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.company = QtWidgets.QLabel(Form)
        self.company.setGeometry(QtCore.QRect(70, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.company.setFont(font)
        self.company.setObjectName("company")
        self.pushButton = QtWidgets.QPushButton(Form,clicked=lambda:self.kayit())
        self.pushButton.setGeometry(QtCore.QRect(280, 140, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 210, 181, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def kayit(self):
        mycursor=mydb.cursor()
        sql="INSERT INTO MAVI (sirket,borc,alinacak) VALUES (%s,%s,%s)"
        val=(self.lineEdit.text(),self.lineEdit_2.text(),self.lineEdit_3.text())
        mycursor.execute(sql,val)
        mydb.commit()
        mydb.close()
        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.company_3.setText(_translate("Form", "ALINACAK"))
        self.company_2.setText(_translate("Form", "BORC"))
        self.company.setText(_translate("Form", "SİRKET ADI"))
        self.pushButton.setText(_translate("Form", "İŞLE"))

mydb = mysql.connector.connect(
     host="localhost",
     user="root",
     password="admin123",
     database="mydatabase"
 )
mycursor=mydb.cursor()



    
